# Hugo configuration
baseURL = "https://nextredo.github.io/"
locale = "en-au"
title = "Mega Epic Website 🌠🌐🔍"
theme = "nojs"
copyright = "🄯 AGPLv3"
# enableGitInfo = true

# Custom parameters
[params]
repo_url = "https://github.com/nextredo/nextredo.github.io"

# Menu items
[menu]
[[menu.main]]
name = "🏡 Home"
url = "/"
weight = 1

[[menu.main]]
name = "🪰 Cool Sites"
url = "/sites/"
weight = 2

[[menu.main]]
name = "📯 Posts"
url = "/posts/"
weight = 3

[[menu.main]]
name = "🏷️ Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "🧐 About"
url = "/about/"
weight = 4
