#!/usr/bin/env bash
#
# A small script to remove sensitive EXIF data from images
# Modelled off https://dunkirk.sh/blog/remove-exif-git-hook/
# See here for ideas on exiftool scripting https://exiftool.org/mistakes.html
# ------------------------------------------------------------------------------

# TODO put this in an actual script
# Debugging nonsense
# Lets you check if it actually removes what it says it does
# Files should look like this:
# /tmp
# ├── test
# │   ├── img.jpg
# │   └── subdir
# │       ├── img.jpg
# │       ├── original (created by the script)
# │       └── stripped (created by the script)
# cd /tmp/test/subdir
# exiftool ../img.jpg > original
# ~/<PATH_TO_REPO>/hooks/pre-commit
# exiftool ./img.jpg > stripped
# grep -Fvxf stripped original
#
# Copy file back for the next run
# cp -f ../img.jpg .

# ANSI Colour Codes
GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m' # No colour

GOOD="${GREEN}SUCCESS${NC}"
BAD="${RED}FAILURE${NC}"

check_ret() {
    # Check return from command called before this function
    if [ $? -eq 0 ]; then
        echo -e "${GOOD}: ${1}"
    else
        echo -e "${BAD}: ${1}" >&2
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# Meat of the script -----------------------------------------------------------
# Check if exiftool is installed (using BASH builtin)
if ! command -v exiftool &> /dev/null; then
    echo "${BAD}: Exiftool is not installed. Please install it." >&2
fi

# Script warning
cat << 'EOF'
------------------------------------------------------------
WARNING:
This script may change files in .gitignore'd locations.
Said stripped files will not show up as changes though.

NOTE:
This script;
- Changes items in directories starting with '.'
- Only changes files supported by exiftool
------------------------------------------------------------

EOF

# Get directories to ignore for exiftool
ignore_flags=$(
    git config --file .gitmodules --get-regexp path | \
        awk '{
            printf "-i ./%s ", $2;
        }
        END {
            print "-i ./.git";
        }'
)
check_ret "Get ignore flags"

# ------------------------------------------------------------------------------
echo "Ignore flags:"
echo "$ignore_flags"
echo ""

echo "Starting exiftool..."

# Print before execute
set -x

# "Wipe everything apart from ..."
# exiftool $ignore_flags -r. -preserve -overwrite_original_in_place \
#     -all= --icc_profile:all --pixel:all -tagsfromfile @ \
#     -orientation -Software -Artist -Copyright -source .

# "Wipe these specific things only"
exiftool $ignore_flags -r. -preserve -overwrite_original_in_place \
    -gps:all= -gps*= -SerialNumber= -LensSerialNumber= \
    -LensIDNumber= -SerialNumber= -LensSerialNumber= \
    -ShutterCount= -Keywords= -Subject= -ThumbnailImage= \
    -PhotoshopThumbnail= -XMP:All= -MakerNotes= .

# Turn off print before execute
{ set +x; } 2>/dev/null

# Verify it exited successfully
check_ret "Run exiftool"
# ------------------------------------------------------------------------------

# Quit happily :)
exit 0
